// Champion data structure
export interface Champion {
    id: number;
    name: string;
    role?: string;
}

// Mock champions data - this will be replaced with API call later
const mockChampions: Champion[] = [
    { id: 1, name: "Aatrox", role: "top" },
    { id: 2, name: "Ahri", role: "mid" },
    { id: 3, name: "Akali", role: "mid" },
    { id: 4, name: "Akshan", role: "mid" },
    { id: 5, name: "Alistar", role: "support" },
    { id: 6, name: "Amumu", role: "jungle" },
    { id: 7, name: "Anivia", role: "mid" },
    { id: 8, name: "Annie", role: "mid" },
    { id: 9, name: "Aphelios", role: "adc" },
    { id: 10, name: "Ashe", role: "adc" },
    { id: 11, name: "Aurelion Sol", role: "mid" },
    { id: 12, name: "Azir", role: "mid" },
    { id: 13, name: "Bard", role: "support" },
    { id: 14, name: "Bel'Veth", role: "jungle" },
    { id: 15, name: "Blitzcrank", role: "support" },
    { id: 16, name: "Brand", role: "support" },
    { id: 17, name: "Braum", role: "support" },
    { id: 18, name: "Caitlyn", role: "adc" },
    { id: 19, name: "Camille", role: "top" },
    { id: 20, name: "Cassiopeia", role: "mid" },
    { id: 21, name: "Cho'Gath", role: "top" },
    { id: 22, name: "Corki", role: "mid" },
    { id: 23, name: "Darius", role: "top" },
    { id: 24, name: "Diana", role: "jungle" },
    { id: 25, name: "Dr. Mundo", role: "top" },
    { id: 26, name: "Draven", role: "adc" },
    { id: 27, name: "Ekko", role: "jungle" },
    { id: 28, name: "Elise", role: "jungle" },
    { id: 29, name: "Evelynn", role: "jungle" },
    { id: 30, name: "Ezreal", role: "adc" },
    { id: 31, name: "Fiddlesticks" },
    { id: 32, name: "Fiora" },
    { id: 33, name: "Fizz" },
    { id: 34, name: "Galio" },
    { id: 35, name: "Gangplank" },
    { id: 36, name: "Garen" },
    { id: 37, name: "Gnar" },
    { id: 38, name: "Gragas" },
    { id: 39, name: "Graves" },
    { id: 40, name: "Gwen" },
    { id: 41, name: "Hecarim" },
    { id: 42, name: "Heimerdinger" },
    { id: 43, name: "Illaoi" },
    { id: 44, name: "Irelia" },
    { id: 45, name: "Ivern" },
    { id: 46, name: "Janna" },
    { id: 47, name: "Jarvan IV" },
    { id: 48, name: "Jax" },
    { id: 49, name: "Jayce" },
    { id: 50, name: "Jhin" },
    { id: 51, name: "Jinx" },
    { id: 52, name: "K'Sante" },
    { id: 53, name: "Kai'Sa" },
    { id: 54, name: "Kalista" },
    { id: 55, name: "Karma" },
    { id: 56, name: "Karthus" },
    { id: 57, name: "Kassadin" },
    { id: 58, name: "Katarina" },
    { id: 59, name: "Kayle" },
    { id: 60, name: "Kayn" },
    { id: 61, name: "Kennen" },
    { id: 62, name: "Kha'Zix" },
    { id: 63, name: "Kindred" },
    { id: 64, name: "Kled" },
    { id: 65, name: "Kog'Maw" },
    { id: 66, name: "LeBlanc" },
    { id: 67, name: "Lee Sin" },
    { id: 68, name: "Leona" },
    { id: 69, name: "Lillia" },
    { id: 70, name: "Lissandra" },
    { id: 71, name: "Lucian" },
    { id: 72, name: "Lulu" },
    { id: 73, name: "Lux" },
    { id: 74, name: "Malphite" },
    { id: 75, name: "Malzahar" },
    { id: 76, name: "Maokai" },
    { id: 77, name: "Master Yi" },
    { id: 78, name: "Milio" },
    { id: 79, name: "Miss Fortune" },
    { id: 80, name: "Mordekaiser" },
    { id: 81, name: "Morgana" },
    { id: 82, name: "Nami" },
    { id: 83, name: "Nasus" },
    { id: 84, name: "Nautilus" },
    { id: 85, name: "Neeko" },
    { id: 86, name: "Nidalee" },
    { id: 87, name: "Nilah" },
    { id: 88, name: "Nocturne" },
    { id: 89, name: "Nunu & Willump" },
    { id: 90, name: "Olaf" },
    { id: 91, name: "Orianna" },
    { id: 92, name: "Ornn" },
    { id: 93, name: "Pantheon" },
    { id: 94, name: "Poppy" },
    { id: 95, name: "Pyke" },
    { id: 96, name: "Qiyana" },
    { id: 97, name: "Quinn" },
    { id: 98, name: "Rakan" },
    { id: 99, name: "Rammus" },
    { id: 100, name: "Rek'Sai" },
    { id: 101, name: "Rell" },
    { id: 102, name: "Renata Glasc" },
    { id: 103, name: "Renekton" },
    { id: 104, name: "Rengar" },
    { id: 105, name: "Riven" },
    { id: 106, name: "Rumble" },
    { id: 107, name: "Ryze" },
    { id: 108, name: "Samira" },
    { id: 109, name: "Sejuani" },
    { id: 110, name: "Senna" },
    { id: 111, name: "Seraphine" },
    { id: 112, name: "Sett" },
    { id: 113, name: "Shaco" },
    { id: 114, name: "Shen" },
    { id: 115, name: "Shyvana" },
    { id: 116, name: "Singed" },
    { id: 117, name: "Sion" },
    { id: 118, name: "Sivir" },
    { id: 119, name: "Skarner" },
    { id: 120, name: "Sona" },
    { id: 121, name: "Soraka" },
    { id: 122, name: "Swain" },
    { id: 123, name: "Sylas" },
    { id: 124, name: "Syndra" },
    { id: 125, name: "Tahm Kench" },
    { id: 126, name: "Taliyah" },
    { id: 127, name: "Talon" },
    { id: 128, name: "Taric" },
    { id: 129, name: "Teemo" },
    { id: 130, name: "Thresh" },
    { id: 131, name: "Tristana" },
    { id: 132, name: "Trundle" },
    { id: 133, name: "Tryndamere" },
    { id: 134, name: "Twisted Fate" },
    { id: 135, name: "Twitch" },
    { id: 136, name: "Udyr" },
    { id: 137, name: "Urgot" },
    { id: 138, name: "Varus" },
    { id: 139, name: "Vayne" },
    { id: 140, name: "Veigar" },
    { id: 141, name: "Vel'Koz" },
    { id: 142, name: "Vex" },
    { id: 143, name: "Vi" },
    { id: 144, name: "Viego" },
    { id: 145, name: "Viktor" },
    { id: 146, name: "Vladimir" },
    { id: 147, name: "Volibear" },
    { id: 148, name: "Warwick" },
    { id: 149, name: "Wukong" },
    { id: 150, name: "Xayah" },
    { id: 151, name: "Xerath" },
    { id: 152, name: "Xin Zhao" },
    { id: 153, name: "Yasuo" },
    { id: 154, name: "Yone" },
    { id: 155, name: "Yorick" },
    { id: 156, name: "Yuumi" },
    { id: 157, name: "Zac" },
    { id: 158, name: "Zed" },
    { id: 159, name: "Zeri" },
    { id: 160, name: "Ziggs" },
    { id: 161, name: "Zilean" },
    { id: 162, name: "Zoe" },
    { id: 163, name: "Zyra" }
];

// Function to fetch champions - will be replaced with API call
export const fetchChampions = async (): Promise<Champion[]> => {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 100));

    // Return mock data - replace this with actual API call later
    return mockChampions;
};

// Function to get champions by IDs (for specific bloodline data)
export const getChampionsByIds = (ids: number[]): Champion[] => {
    return mockChampions.filter(champion => ids.includes(champion.id));
}; 